const fs = require('fs');
let c = fs.readFileSync('app/cart/page.js', 'utf8').split('\n');
c.splice(980, c.length - 980,
'                                <div>',
'                                    <p className="text-[12px] font-bold text-[#303030] leading-tight">Easy Returns</p>',
'                                    <p className="text-[11px] text-gray-500">7 Days Return</p>',
'                                </div>',
'                            </div>',
'                            <div className="flex flex-col items-center text-center gap-2 border-l border-[#F2EAE3]">',
'                                <div className="text-[#135B42] opacity-80"><ShieldCheck size={28} /></div>',
'                                <div>',
'                                    <p className="text-[12px] font-bold text-[#303030] leading-tight">Secure Payment</p>',
'                                    <p className="text-[11px] text-gray-500">100% Safe</p>',
'                                </div>',
'                            </div>',
'                            <div className="flex flex-col items-center text-center gap-2 border-l border-[#F2EAE3]">',
'                                <div className="text-[#135B42] opacity-80"><Truck size={28} /></div>',
'                                <div>',
'                                    <p className="text-[12px] font-bold text-[#303030] leading-tight">Fast & Safe</p>',
'                                    <p className="text-[11px] text-gray-500">Delivery</p>',
'                                </div>',
'                            </div>',
'                        </div>',
'                        </>',
'                    )}',
'                </div>',
'            </div>',
'            ',
'            <Footer />',
'',
'            {/* Clear Cart Confirmation Modal */}',
'            {showClearModal && (',
'                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in">',
'                    <div className="bg-white rounded-xl shadow-xl w-full max-w-md overflow-hidden animate-scale-in">',
'                        <div className="p-6 text-center">',
'                            <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4 text-red-500">',
'                                <Trash2 size={32} />',
'                            </div>',
'                            <h3 className="text-xl font-bold text-gray-900 mb-2 font-playfair">Clear Entire Bag?</h3>',
'                            <p className="text-gray-500 text-[14px]">',
'                                Are you sure you want to remove all items from your shopping bag? This action cannot be undone.',
'                            </p>',
'                        </div>',
'                        <div className="flex border-t border-gray-100">',
'                            <button ',
'                                onClick={() => setShowClearModal(false)}',
'                                className="flex-1 py-4 text-gray-600 font-medium hover:bg-gray-50 transition-colors"',
'                            >',
'                                Cancel',
'                            </button>',
'                            <button ',
'                                onClick={executeClearBag}',
'                                className="flex-1 py-4 text-red-600 font-medium hover:bg-red-50 border-l border-gray-100 transition-colors"',
'                            >',
'                                Yes, Clear Bag',
'                            </button>',
'                        </div>',
'                    </div>',
'                </div>',
'            )}',
'        </main>',
'    );',
'}',
);
fs.writeFileSync('app/cart/page.js', c.join('\n'));
console.log('Fixed');
